from typing import Protocol


class WebhookRegistryPort(Protocol):
    def init_db(self) -> None: ...

    def register_webhook(self, webhook: str, secret: str) -> None: ...

    def get_webhook_registration(self, webhook: str) -> dict[str, object] | None: ...

    def list_webhook_registrations(self) -> list[dict[str, object]]: ...

    def remove_webhook(self, webhook: str) -> bool: ...
